### ISSUE TITLE
Воркшоп по сборке датчиков оценки качества воздуха

### ISSUE THREAD

**Issue by dcromster** [in100gramm/events#18]
- Начало: 12:00
- Тип: открытое (по приглашениям)
- Обсуждение: https://t.me/breathespb
- Организатор: твиттер https://twitter.com/uncle_robot телеграм: @rominsky (питерский чел), телеграмчик @petrov1c (главбосс, Москва)

Хотелось бы на 3 часа. Количество человек: ожидаем до 20.

**Comment by Realetive** [comment]
@dcromster, место точно подходит? Там 16 посадочных мест, но они не как в учебном классе:

```
    +               +
    |   Б  А  Р     |
    +---------------+
        1   2   3    4
+---+               +-+
|   |               | |
|   |16    11       +-+
|   |    +-----+     5
|   |  12|     |10  +-+
|   |    |     |    | |
|   |  13|     |9   +-+
|   |    |     |     6
|   |  14|     |8   +-+
|   |    |     |    | |
+---+  15+-----+7   +-+
```

Цифрами условно обозначил сидячие места.

**Comment by Realetive** [comment]
@dcromster я сегодня узнаю про вариант в другом баре, «Творчестве» на Гороховой ул., 68 — там полноценный зал и можно будет сдвинуть столы. Пайка планируется?

**Comment by dcromster** [comment]
Спасибо!
Если там удобнее и нас примут, то можно там.

**Comment by Realetive** [comment]
Перенесли мероприятие в «Творчество».
